@host = http://localhost:5000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVmMTcwYTRhNjY0N2ZjN2JkMDA2NjhhMyJ9LCJpYXQiOjE1OTUzNDcxNDl9.5QxJTbk9nZYgKOX9UNRmpYt0Hps_xdV4obIx4ujlbp0

GET {{host}}/api/users/user_data
Authorization: Bearer {{token}}

###

GET {{host}}/api/tickets?page=1&limit=8

###

POST {{host}}/api/auth/signup
Content-Type: application/json

{
    "username": "y4mm",
    "email": "aa@home.com",
    "password": "123456"
}

###

POST {{host}}/api/auth/login
Content-Type: application/json

{
    "username": "y4mm1",
    "password": "123456"
}

###

GET {{host}}/api/users/admin
Authorization: Bearer {{token}}