@host = http://localhost:5000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjVkYmExYjE2ZWM1YmNkNGY4Y2UwMmZhMSJ9LCJpYXQiOjE1NzUyMTUyOTMsImV4cCI6MTU3NTIxODI5M30.WMhbFhuZViuCBh5R0s_1j1D1y6hcnLBLrfnTV9mTD18

GET {{host}}/api/users/user_data
Authorization: Bearer {{token}}

###

GET {{host}}/api/tickets?page=1&limit=8

###

POST {{host}}/api/auth/signup
Content-Type: application/json

{
    "username": "admin",
    "email": "a",
    "password": "1236"
}

###

POST {{host}}/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}